/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnlString.java
 *
 * Created on Aug 23, 2009, 11:56:59 PM
 */
package pspconstructor.Properties;

import pspconstructor.Components.GCBackground;
import pspconstructor.Components.GCFont;
import pspconstructor.Components.GCHandler;
import pspconstructor.Components.GCObject;
import pspconstructor.Components.GCParticle;
import pspconstructor.Components.GCSound;
import pspconstructor.Components.GCSprite;
import pspconstructor.Components.GCWorld;

/**
 *
 * @author Carlo
 */
public class pnlComponent extends javax.swing.JPanel {

    /** Creates new form pnlString */
    public pnlComponent(String Type) {
        initComponents();
        if (Type.equals("Sprite")) {
            for (GCSprite s : GCHandler.Sprites) {
                cboComp.addItem(s.Name);
            }
        } else if (Type.equals("Sound")) {
            for (GCSound s : GCHandler.Sounds) {
                cboComp.addItem(s.Name);
            }
        } else if (Type.equals("Background")) {
            for (GCBackground s : GCHandler.Backgrounds) {
                cboComp.addItem(s.Name);
            }
        } else if (Type.equals("Particle")) {
            for (GCParticle s : GCHandler.Particles) {
                cboComp.addItem(s.Name);
            }
        } else if (Type.equals("Font")) {
            for (GCFont s : GCHandler.Fonts) {
                cboComp.addItem(s.Name);
            }
        } else if (Type.equals("Object")) {
            for (GCObject s : GCHandler.Objects) {
                cboComp.addItem(s.Name);
            }
        } else if (Type.equals("World")) {
            for (GCWorld s : GCHandler.Worlds) {
                cboComp.addItem(s.Name);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArg = new javax.swing.JLabel();
        cboComp = new javax.swing.JComboBox();

        lblArg.setText("Argument:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(cboComp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblArg)
                .addComponent(cboComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox cboComp;
    public javax.swing.JLabel lblArg;
    // End of variables declaration//GEN-END:variables
}
