package pspconstructor.Properties;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Carlo
 */
public class pnlColor extends javax.swing.JPanel {

    Color color;

    /** Creates new form pnlColor */
    public pnlColor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblArg = new javax.swing.JLabel();
        btnArg = new javax.swing.JButton();

        lblArg.setText("Argument:");

        btnArg.setText("Edit");
        btnArg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblArg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btnArg))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnArg)
                .addComponent(lblArg))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnArgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArgActionPerformed
        color = JColorChooser.showDialog(null, "Choose a color",color);
    }//GEN-LAST:event_btnArgActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnArg;
    public javax.swing.JLabel lblArg;
    // End of variables declaration//GEN-END:variables
}
